DELETE FROM STUDY_ROOM_RESERVE_TYPE;
DELETE FROM STUDY_ROOM_TAG;
DELETE FROM STUDY_ROOM_IMAGE;
DELETE FROM STUDY_ROOM_OPTION_INFO;
DELETE FROM STUDY_ROOM_TYPE_INFO;
DELETE FROM STUDY_ROOM_DAY_OFF;
DELETE FROM STUDY_ROOM_LIKE;
DELETE FROM STUDY_ROOM_BOOKMARK;
DELETE FROM STUDY_ROOM_REVIEW;
DELETE FROM STUDY_ROOM_QNA;
DELETE FROM STUDY_ROOM;
DELETE FROM USERS;
SELECT setval('study_room_image_id_seq', 1, false);
SELECT setval('study_room_tag_id_seq', 1, false);
SELECT setval('study_room_day_off_id_seq', 1, false);
SELECT setval('study_room_option_info_id_seq', 1, false);
SELECT setval('study_room_type_info_id_seq', 1, false);
SELECT setval('study_room_reserve_type_id_seq', 1, false);
SELECT setval('study_room_bookmark_id_seq', 1, false);
SELECT setval('study_room_id_seq', 1, false);
