ALTER TYPE study_category ADD VALUE IF NOT EXISTS 'EXAM';
ALTER TYPE study_category ADD VALUE IF NOT EXISTS 'LANGUAGE';
ALTER TYPE study_category ADD VALUE IF NOT EXISTS 'READING';
ALTER TYPE study_category ADD VALUE IF NOT EXISTS 'DISCUSSION';
ALTER TYPE study_category ADD VALUE IF NOT EXISTS 'CAREER';
ALTER TYPE study_category ADD VALUE IF NOT EXISTS 'HOBBY';
