create table if not exists study_room(
    id bigserial primary key,
    user_id uuid not null,
    title varchar(100) not null,
    subtitle varchar(100) null,
    introduce text not null,
    notice text not null,
    thumbnail varchar(300) not null,
    opening_time time not null,
    closing_time time not null,
    guideline text not null,
    address varchar(100) not null,
    detail_address varchar(100) not null,
    region varchar(20) not null,
    locality varchar(20) not null,
    latitude double precision null,
    longitude double precision null,
    reference_url varchar(300) null,
    phone_number varchar(20) not null,
    like_count integer not null default 0,
    review_count integer not null default 0,
    average_rating double precision not null default 0,
    deleted_at timestamp null,
    created_at timestamp not null,
    updated_at timestamp not null
)
